/**
 * テスト用モックデータ
 * CPMスケジューリング機能のテスト用のサンプルタスクデータ
 */

import { Task } from '../types/task';

/**
 * サンプルタスクデータを生成
 */
export function generateMockTasks(projectId: string): Task[] {
  const today = new Date();
  const oneDay = 24 * 60 * 60 * 1000;

  return [
    {
      id: 'task-1',
      projectId: projectId,
      parentId: null,
      wbsCode: '1',
      name: 'プロジェクト計画フェーズ',
      description: 'プロジェクトの計画と準備',
      type: 'summary',
      status: 'in_progress',
      priority: 'high',
      plannedStartDate: new Date(today.getTime()),
      plannedEndDate: new Date(today.getTime() + 30 * oneDay),
      actualStartDate: new Date(today.getTime()),
      actualEndDate: null,
      duration: 30,
      remainingDuration: 20,
      percentComplete: 33,
      physicalPercentComplete: 30,
      assignedResources: [],
      dependencies: [],
      budgetedCost: 1000000,
      actualCost: 330000,
      remainingCost: 670000,
      sortOrder: 1,
      notes: '',
      tags: ['計画'],
      createdAt: new Date(),
      updatedAt: new Date(),
      cpm: {
        earlyStart: new Date(today.getTime()),
        earlyFinish: new Date(today.getTime() + 30 * oneDay),
        lateStart: new Date(today.getTime()),
        lateFinish: new Date(today.getTime() + 30 * oneDay),
        totalFloat: 0,
        freeFloat: 0,
        isCritical: true,
      },
      constraints: [],
    },
    {
      id: 'task-2',
      projectId: projectId,
      parentId: 'task-1',
      wbsCode: '1.1',
      name: '要件定義',
      description: 'システム要件の定義と分析',
      type: 'task',
      status: 'completed',
      priority: 'high',
      plannedStartDate: new Date(today.getTime()),
      plannedEndDate: new Date(today.getTime() + 10 * oneDay),
      actualStartDate: new Date(today.getTime()),
      actualEndDate: new Date(today.getTime() + 10 * oneDay),
      duration: 10,
      remainingDuration: 0,
      percentComplete: 100,
      physicalPercentComplete: 100,
      assignedResources: [],
      dependencies: [],
      budgetedCost: 300000,
      actualCost: 300000,
      remainingCost: 0,
      sortOrder: 1,
      notes: '完了',
      tags: ['要件'],
      createdAt: new Date(),
      updatedAt: new Date(),
      cpm: {
        earlyStart: new Date(today.getTime()),
        earlyFinish: new Date(today.getTime() + 10 * oneDay),
        lateStart: new Date(today.getTime()),
        lateFinish: new Date(today.getTime() + 10 * oneDay),
        totalFloat: 0,
        freeFloat: 0,
        isCritical: true,
      },
      constraints: [],
    },
    {
      id: 'task-3',
      projectId: projectId,
      parentId: 'task-1',
      wbsCode: '1.2',
      name: '基本設計',
      description: 'システムの基本設計',
      type: 'task',
      status: 'in_progress',
      priority: 'high',
      plannedStartDate: new Date(today.getTime() + 10 * oneDay),
      plannedEndDate: new Date(today.getTime() + 20 * oneDay),
      actualStartDate: new Date(today.getTime() + 10 * oneDay),
      actualEndDate: null,
      duration: 10,
      remainingDuration: 7,
      percentComplete: 30,
      physicalPercentComplete: 25,
      assignedResources: [],
      dependencies: [
        { predecessorId: 'task-2', type: 'FS', lag: 0 }
      ],
      budgetedCost: 400000,
      actualCost: 120000,
      remainingCost: 280000,
      sortOrder: 2,
      notes: '進行中',
      tags: ['設計'],
      createdAt: new Date(),
      updatedAt: new Date(),
      cpm: {
        earlyStart: new Date(today.getTime() + 10 * oneDay),
        earlyFinish: new Date(today.getTime() + 20 * oneDay),
        lateStart: new Date(today.getTime() + 10 * oneDay),
        lateFinish: new Date(today.getTime() + 20 * oneDay),
        totalFloat: 0,
        freeFloat: 0,
        isCritical: true,
      },
      constraints: [],
    },
    {
      id: 'task-4',
      projectId: projectId,
      parentId: 'task-1',
      wbsCode: '1.3',
      name: 'プロトタイプ作成',
      description: 'プロトタイプの作成とレビュー',
      type: 'task',
      status: 'not_started',
      priority: 'normal',
      plannedStartDate: new Date(today.getTime() + 20 * oneDay),
      plannedEndDate: new Date(today.getTime() + 30 * oneDay),
      actualStartDate: null,
      actualEndDate: null,
      duration: 10,
      remainingDuration: 10,
      percentComplete: 0,
      physicalPercentComplete: 0,
      assignedResources: [],
      dependencies: [
        { predecessorId: 'task-3', type: 'FS', lag: 0 }
      ],
      budgetedCost: 300000,
      actualCost: 0,
      remainingCost: 300000,
      sortOrder: 3,
      notes: '',
      tags: ['プロトタイプ'],
      createdAt: new Date(),
      updatedAt: new Date(),
      cpm: {
        earlyStart: new Date(today.getTime() + 20 * oneDay),
        earlyFinish: new Date(today.getTime() + 30 * oneDay),
        lateStart: new Date(today.getTime() + 20 * oneDay),
        lateFinish: new Date(today.getTime() + 30 * oneDay),
        totalFloat: 0,
        freeFloat: 0,
        isCritical: true,
      },
      constraints: [],
    },
    {
      id: 'task-5',
      projectId: projectId,
      parentId: null,
      wbsCode: '2',
      name: '実装フェーズ',
      description: 'システムの実装',
      type: 'summary',
      status: 'not_started',
      priority: 'high',
      plannedStartDate: new Date(today.getTime() + 30 * oneDay),
      plannedEndDate: new Date(today.getTime() + 60 * oneDay),
      actualStartDate: null,
      actualEndDate: null,
      duration: 30,
      remainingDuration: 30,
      percentComplete: 0,
      physicalPercentComplete: 0,
      assignedResources: [],
      dependencies: [
        { predecessorId: 'task-4', type: 'FS', lag: 0 }
      ],
      budgetedCost: 2000000,
      actualCost: 0,
      remainingCost: 2000000,
      sortOrder: 2,
      notes: '',
      tags: ['実装'],
      createdAt: new Date(),
      updatedAt: new Date(),
      cpm: {
        earlyStart: new Date(today.getTime() + 30 * oneDay),
        earlyFinish: new Date(today.getTime() + 60 * oneDay),
        lateStart: new Date(today.getTime() + 30 * oneDay),
        lateFinish: new Date(today.getTime() + 60 * oneDay),
        totalFloat: 0,
        freeFloat: 0,
        isCritical: true,
      },
      constraints: [],
    },
    {
      id: 'task-6',
      projectId: projectId,
      parentId: 'task-5',
      wbsCode: '2.1',
      name: 'フロントエンド実装',
      description: 'フロントエンドの実装',
      type: 'task',
      status: 'not_started',
      priority: 'high',
      plannedStartDate: new Date(today.getTime() + 30 * oneDay),
      plannedEndDate: new Date(today.getTime() + 45 * oneDay),
      actualStartDate: null,
      actualEndDate: null,
      duration: 15,
      remainingDuration: 15,
      percentComplete: 0,
      physicalPercentComplete: 0,
      assignedResources: [],
      dependencies: [
        { predecessorId: 'task-4', type: 'FS', lag: 0 }
      ],
      budgetedCost: 800000,
      actualCost: 0,
      remainingCost: 800000,
      sortOrder: 1,
      notes: '',
      tags: ['フロントエンド'],
      createdAt: new Date(),
      updatedAt: new Date(),
      cpm: {
        earlyStart: new Date(today.getTime() + 30 * oneDay),
        earlyFinish: new Date(today.getTime() + 45 * oneDay),
        lateStart: new Date(today.getTime() + 35 * oneDay),
        lateFinish: new Date(today.getTime() + 50 * oneDay),
        totalFloat: 5,
        freeFloat: 5,
        isCritical: false,
      },
      constraints: [],
    },
    {
      id: 'task-7',
      projectId: projectId,
      parentId: 'task-5',
      wbsCode: '2.2',
      name: 'バックエンド実装',
      description: 'バックエンドの実装',
      type: 'task',
      status: 'not_started',
      priority: 'high',
      plannedStartDate: new Date(today.getTime() + 30 * oneDay),
      plannedEndDate: new Date(today.getTime() + 50 * oneDay),
      actualStartDate: null,
      actualEndDate: null,
      duration: 20,
      remainingDuration: 20,
      percentComplete: 0,
      physicalPercentComplete: 0,
      assignedResources: [],
      dependencies: [
        { predecessorId: 'task-4', type: 'FS', lag: 0 }
      ],
      budgetedCost: 1000000,
      actualCost: 0,
      remainingCost: 1000000,
      sortOrder: 2,
      notes: '',
      tags: ['バックエンド'],
      createdAt: new Date(),
      updatedAt: new Date(),
      cpm: {
        earlyStart: new Date(today.getTime() + 30 * oneDay),
        earlyFinish: new Date(today.getTime() + 50 * oneDay),
        lateStart: new Date(today.getTime() + 30 * oneDay),
        lateFinish: new Date(today.getTime() + 50 * oneDay),
        totalFloat: 0,
        freeFloat: 0,
        isCritical: true,
      },
      constraints: [],
    },
    {
      id: 'task-8',
      projectId: projectId,
      parentId: 'task-5',
      wbsCode: '2.3',
      name: '統合テスト',
      description: '統合テストの実施',
      type: 'task',
      status: 'not_started',
      priority: 'high',
      plannedStartDate: new Date(today.getTime() + 50 * oneDay),
      plannedEndDate: new Date(today.getTime() + 60 * oneDay),
      actualStartDate: null,
      actualEndDate: null,
      duration: 10,
      remainingDuration: 10,
      percentComplete: 0,
      physicalPercentComplete: 0,
      assignedResources: [],
      dependencies: [
        { predecessorId: 'task-6', type: 'FS', lag: 0 },
        { predecessorId: 'task-7', type: 'FS', lag: 0 }
      ],
      budgetedCost: 200000,
      actualCost: 0,
      remainingCost: 200000,
      sortOrder: 3,
      notes: '',
      tags: ['テスト'],
      createdAt: new Date(),
      updatedAt: new Date(),
      cpm: {
        earlyStart: new Date(today.getTime() + 50 * oneDay),
        earlyFinish: new Date(today.getTime() + 60 * oneDay),
        lateStart: new Date(today.getTime() + 50 * oneDay),
        lateFinish: new Date(today.getTime() + 60 * oneDay),
        totalFloat: 0,
        freeFloat: 0,
        isCritical: true,
      },
      constraints: [],
    },
  ];
}
